version: '3.7'

services:

  test-openj9:
    image: test-openj9:1.0.0
    container_name: test-openj9
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080

  test-graalvm:
    image: test-graalvm:1.0.0
    container_name: test-graalvm
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081

  test-openjdk:
    image: test-openjdk:1.0.0
    container_name: test-openjdk
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082

  test-zulu:
    image: test-zulu:1.0.0
    container_name: test-zulu
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8083

